### ISSUE TITLE
Payments fail reason=remote can't afford increased commit tx fees once new HTLC is added

### ISSUE THREAD

**Issue by pcwd** [ACINQ/phoenix#103]
I keep getting this error when making a payment. 

cannot add htlc with origin=Local(78cd666a-6c91-425b-af63-950241d83e9c,Some(Actor[akka://system/user/$l/payment-initiator/$b/$a#731706648])) reason=remote can't afford increased commit tx fees once new HTLC is added: missing=Satoshi(2743) reserve=Satoshi(0) fees=Satoshi(26109)

I get this error when I try and send to a bitcoin address.

desc: 449829 sats to bc1qpja3ewkr0g4rjj84ncd5yz2g7zu9tr6ktrv9qh with feerate=110 sat/byte

error: cannot add htlc with origin=Local(32fdd74b-b523-4a0e-9b9b-473e4d67f075,Some(Actor[akka://system/user/$l/payment-initiator/$c/$h#254281781])) reason=remote can't afford increased commit tx fees once new HTLC is added: missing=Satoshi(2743) reserve=Satoshi(0) fees=Satoshi(26109)

**Comment by dpad85** [comment]
Hello,

This error means that making the payment would not leave enough money for the peer in the channel's reserve (which is useful in case a problem happens), so the payment is rejected. It's particularly related to the current on-chain fees, and it happens when the feerate varies a lot. That's something we'd like to improve ; for now, what you can do is lower the amount you're sending to this address if that's possible.

You can also use the `Close all channels` feature. It will do an on-chain tx (or txs if you have several channels). Just note that it will send **all** your balance to that address and you cannot change the feerates.
