### ISSUE TITLE
Firebase Cloud Messaging on Android without Google Play Services

### ISSUE THREAD

**Issue by ndalliard** [ACINQ/phoenix#109]
Will the app work on a Android phone without Google Play Services?

I am asking, because you added Firebase Cloud Messaging in Phoenix 1.4.0 and as far as I know, Google Play Services are needed for that to work.

**Comment by ndalliard** [comment]
I just updated the app and it looks like everything is working fine (didn't test the new feature).

**Comment by dpad85** [comment]
Hi sorry for the delay. If you don't have Google Play Services on your device, then your app cannot be pinged by the peer when it's off and so it cannot wake up. The background payment reception will not work, but that's all. The rest of the app should work fine, it does not depend on Google services.

As a side note, it would be nice to have a messaging system that does not depend on Google, but there are 2 hard requirements: 
- be fast: the peer is actually pausing the payment and waits for the app to wake up and start. However it cannot wait for a long time, because there's potentially a long list of nodes upstream waiting for the payment to fulfill, including the sender of the payment.
- maintain a persistent connection: the messaging system must be able to survive Android's Doze + all the various battery optimizations that vendors like to add. If the OS kills it as an "optimization", it's useless.
