### ISSUE TITLE
general temporary failure of the processing node

### ISSUE THREAD

**Issue by janfiedler** [ACINQ/phoenix#113]
Hi,
in last 24 hours I get always error "general temporary failure of the processing node" when sending from one Phoenix wallet to another Phoenix wallet.

Both with last version of application. And sufficient size of inbound capacity in channels.

Any idea how solve this?

Thank you

**Comment by t-bast** [comment]
This is due to the current mempool issues. The bitcoin mempool is full, thus the fees are incredibly high, and it unfortunately has an impact on incoming channel liquidity which isn't correctly reflected by the app.

We will improve this in the next Phoenix release. Meanwhile you simply need to wait for the mempool to clear and everything will be back to normal.

**Comment by janfiedler** [comment]
Thank you for quick answer.
So even when two Phoenix wallets have a lot of free channel (inboud) capacity can be problem due to fees on main bitcoin layer? 
For example channel 135511 sat / 265 968 sat on incoming side cannot receive 4000 sats due to this? Thanks

**Comment by t-bast** [comment]
Unfortunately yes, because we don't show in Phoenix that part of the *receiving* liquidity is in fact "locked" to handle a potential channel close. The amount locked depends on the on-chain feerate, and since it's huge right now, it locks ~150000 sats of receiving capacity...

We will improve this two-fold: show it in the app when it happens, and longer term we'll prevent this from happening at all.

**Comment by janfiedler** [comment]
Perfect, thank you very much.
