### ISSUE TITLE
No route for incoming payment

### ISSUE THREAD

**Issue by sendbitcoin** [ACINQ/phoenix#123]
I can't seem to send a payment to phoenix from my well connected node. (current lnd + RTL)

I always receive "no_route" error immediatly. the amount does not matter as its the same even with an invoice with no amount.

I have 3 channels with plenty incoming balance in phoenix and in the past I did manage to receive a lightning payment that i sent from BLW (which created one of the channels). 

currently I can't seem to be able to receive any payments that are sent by lnd with phoenix.

testing it with a different node + joule and it also tells me "unable to find node". I tried with the app open but it doesnt seem to make a difference.

Even if I force the first route as Acinq I still receive "no_route". 

Any ideas why?

**Comment by t-bast** [comment]
Can you share a `payment_hash`? We can then verify whether the payment reached our node or not.
But if the payment instantly failed, there is a chance the issue is your node's path-finding (which we'll be able to confirm when you share a `payment_hash`).

Can you also check your node's logs? There may be information in there about why the payment failed (if it's a path-finding failure on your side).

**Comment by sendbitcoin** [comment]
@t-bast It works now...

What changed? 

maybe the channels werent confirmed?

or version 1.4.4 fixed it?

any ideas why it didn't work before but does now even though i didn't really change anything?

**Comment by t-bast** [comment]
I just checked your invoice in our node's logs, the payment never reached the ACINQ node.
The issue is not in Phoenix nor on the ACINQ node, the issue is with your lnd node.
You should investigate your lnd logs to figure out why path-finding failed.
Can you paste your node's logs for this `payment_hash` (`d3799f7bbd9a595a4a8d42677136086c90771e0051852c2e5b318b0cc38c6e01`)?

**Comment by sendbitcoin** [comment]
Ok I just got 1 payment to work (100k sats) by switching of bad wifi and using 4g (i think). guess when your on wifi that just barely works that's a problem?

but immediatly after i tried another transaction and it fails (65432 sats)


INFO: PayReq => Payment Decode Received: {"destination":"02078e2f2d46ce41a8955e02e8761e6e4debcb2412286a5927891bce0d91f4d169","payment_hash":"913c7230e96197ba7c19a57f5217f51bb901f8242b83fc0b0b86b1de3231d9cd","num_satoshis":"0","timestamp":"1608123447","expiry":"604800","description":"","description_hash":"","fallback_addr":"","cltv_expiry":"9","route_hints":[{"hop_hints":[{"node_id":"03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f","chan_id":"18382512861721448809","fee_base_msat":1000,"fee_proportional_millionths":100,"cltv_expiry_delta":144}]}],"payment_addr":"TywTvJquhiosL2sXQCrnzcXV9iRBciRSSayjBrhpS5E=","num_msat":"0","features":{"9":{"name":"tlv-onion","is_required":false,"is_known":true},"15":{"name":"payment-addr","is_required":false,"is_known":true},"17":{"name":"multi-path-payments","is_required":false,"is_known":true},"51":{"name":"unknown","is_required":false,"is_known":false}}}

INFO: Channels => Send Payment Options: {"payment_hash_string":"913c7230e96197ba7c19a57f5217f51bb901f8242b83fc0b0b86b1de3231d9cd","final_cltv_delta":9,"amt":"65432","dest_string":"02078e2f2d46ce41a8955e02e8761e6e4debcb2412286a5927891bce0d91f4d169"}

INFO: Channels => Send Payment Response: {"payment_error":"no_route","payment_preimage":null,"payment_route":null,"payment_hash":"kTxyMOlhl7p8GaV/Uhf1G7kB+CQrg/wLC4ax3jIx2c0="}

ERROR: Channels(206) => Send Payment Error: "no_route"


2 of the channels i have in phoenix should be able to receive this tx and all channels are up and running

**Comment by t-bast** [comment]
> ERROR: Channels(206) => Send Payment Error: "no_route"

This indicates that your lnd node cannot find a route to Phoenix, so again, _the error is not on the Phoenix side, it's in the path-finding of your lnd_ node. Your node doesn't even try to send the payment (this is confirmed on our side, the ACINQ node never received a payment attempt for that payment_hash).

Please open an issue in `lnd` and give them your node's logs, that should help them figure out why path-finding fails.
Maybe they internally "ban" your channel ids because they are private channels, or because a previous error was returned in the past.
