### ISSUE TITLE
"payment amount was below the minimum required by the channel"

### ISSUE THREAD

**Issue by flashtheman** [ACINQ/phoenix#125]
I wanted to send pay an invoice received from another Phonix user but the payment failed with the error "payment amount was below the minimum required by the channel". We tried 100 Satoshi, 200 Satoshi and 1000 Satshoi, all failed. Would you like to analyze this payment? If yes, which information do you need?

**Comment by t-bast** [comment]
That means the receiving Phoenix doesn't have liquidity (i.e. available channels to receive).
The only solution for the payment to go through is to create a channel on-the-fly, but we don't do that for amounts smaller than 10000 satoshis, hence the error message.

**Comment by flashtheman** [comment]
Thanks for the answer. Are there plans to change that in the future? I would never have found out what the problem was and the person I was sending funds to couldn't tell me either.

I was sending 200 satoshi to another non-technical user yesterday (to a breez wallet) and it worked fine.

**Comment by t-bast** [comment]
We will improve the messaging in the app to explain this, but we won't open channels for such tiny amounts.
It's simply not economically scalable, the on-chain fees we pay for the channel creation cost a lot more than the payment amount.

Other wallets like Breez are still opening channels for free because there are few users, but they won't be able to do that forever; they're doing it at a loss (like we do) and at some point they'll need their service to be economically viable.

**Comment by t-bast** [comment]
If you want a new channel to be created (first time the recipient receives a payment for example), you'll need to commit to a large enough amount (right now this is 10 000 sat). Then once that initial payment is done, you can send tiny amounts like 100 sats because there will be a channel available.

**Comment by flashtheman** [comment]
Ok thanks! I anyway hope that this won't be a show stopper for normal users in the future - I hope somehow channels can be totally abstracted away. Thanks for the explanation.

**Comment by t-bast** [comment]
We hope it won't, unfortunately it doesn't make sense to sponsor channels for ridiculously low amounts, we have to set a limit.
But we hope users understand that this is something that happens very unfrequently (when they don't have any receiving capacity anymore), and when that happens they need some kind of medium-size "top-up" payment and then everything is back to normal.

**Comment by flashtheman** [comment]
> "when they don't have any receiving capacity anymore"

What do you mean with "anymore"? I thought as soon as a channel is open, the receiving capacity shouldn't change (as long as the partner nodes don't lower their capacity.

**Comment by t-bast** [comment]
No that's not how it works.

If you have for example two nodes A and B, and B opens a 100 000 sats channel to A.
At first all the funds are on B's side, so A is able to receive 100 000 sat on this channel (ignoring fees for simplicity).
But if A receives for example a payment of 15 000 sat, now the balance is B=85000 sat and A=15000 sats, so now A can only receive 85000 sats on this channel.

If A makes outgoing payments, then she will be able to receive more, but the amount she can receive depends on how the funds are split inside the channel. The channel capacity is only the *maximum* amount you can receive on that channel. If you look at your channels list in Phoenix, you'll see that how much you can receive evolves when you make payments.

**Comment by flashtheman** [comment]
Understood. Thanks a lot for explaining this basic lightning know how!!!

**Comment by jivanpal** [comment]
> we don't do that for amounts smaller than 10000 satoshis, hence the error message.

The 10,000 sats figure really needs to be started in the so when this error occurs or when the invoice is generated and the expected channel set-up fee is displayed. As is, I had to search the web for the vague error message "payment amount is too low" in order to find out what the threshold for "too low" actually is. This GitHub issue was the second Google result, and first relevant result.
