### ISSUE TITLE
11k sat transaction sent/received - zero balance, no channel created 

### ISSUE THREAD

**Issue by jk14** [ACINQ/phoenix#139]
From first Phoenix wallet I made 11k sat transfer to another, freshly created Phoenix wallet.
Transaction was sent properly, and properly received 10k sat on the other end. But available balance is still 0 and no channel in Settings -> Channels List. Fresh Phoenix wallet looks like this:

https://imgur.com/a/pdVRXSg

What to do now?

**Comment by pm47** [comment]
Sorry about that, a regression on our node. Should be fixed now if you restart Phoenix

**Comment by jk14** [comment]
restart or reinstall? I forced switch-off the application and start - and there is no effect of it...

**Comment by pm47** [comment]
Yeah, you're right, this is just fixing future channels. This is going to take a bit longer stay tuned

**Comment by pm47** [comment]
Ok, should be good now.

**Comment by jk14** [comment]
yes, fixed! thank you

btw, what if I would send 10k? 9k on the other end is enough?
(if not - that in fact 11k sat requirement - should be more highlighted, imo)

**Comment by pm47** [comment]
The reaon for this bug is that we accidentally pushed an update to the node that required Phoenix to also be updated. It should have been done the other way: first Phoenix then our node.

> btw, what if I would send 10k? 9k on the other end is enough?
(if not - that in fact 11k sat requirement - should be more highlighted, imo)

You should be able to send 10k, Phoenix will receive 9k. Just tried on testnet

**Comment by jk14** [comment]
works with 10k/9k on mainnet, too
(wen iOS? ;)
