### ISSUE TITLE
On chain fee rate defaults to 20+ sat/byte

### ISSUE THREAD

**Issue by blankscreengithub** [ACINQ/phoenix#157]
If I send back to an on chain address and I select a low fee like 10 sat/byte, the app sends the transaction out at 20+ sat/byte. This is a bug, because if I set a lower fee, I expect to pay the lower fee. It's like the lowest fee the app will do is 20+, but it still lets you set a lower fee leading the user believe they are using a lower fee.

**Comment by dpad85** [comment]
That's because the swap service doing the lightning -> on-chain swap has its own minimum fee. The wallet can request a low fee but it does not mean it is going to be accepted by the service. That is why there is a confirmation screen that recaps before sending the payment how much you would pay and what the actual fee would be.

In any case having a user-defined fee rate does not work well. Some want to use a low fee, others are in a hurry, but the UTXOs set is shared between all these users so this makes for a frustrating experience. I think we will remove this customizable fee rate  and swaps will all use the same fee rate at a given time (that's what we had initially).

**Comment by blankscreengithub** [comment]
The non-adjustable fee rate makes sense for system wide consistency.

Also, the confirmation screen gives total fee in sats and fiat, not sat/byte.
