### ISSUE TITLE
missing feature dependency: 9

### ISSUE THREAD

**Issue by grunch** [ACINQ/phoenix#18]
I'm trying to pay a phoenix invoice from my lnd node but I get this message

```
{
    "payment_error": "missing feature dependency: 9",
    "payment_preimage": null,
    "payment_route": null,
    "payment_hash": "ad65903688e74100028a95814fc7b1e1f41d8441deaa278c2588998c13c03940"
}
```
According with lalou the invoice is missing the onion tlv, which is needed in order to use mpp.

And in fact if I decoded the phoenix invoice I don't see feature 9 tlv-onion
```
    "features": {
        "15": {
            "name": "payment-addr",
            "is_required": false,
            "is_known": true
        },
        "17": {
            "name": "multi-path-payments",
            "is_required": false,
            "is_known": true
        },
        "51": {
            "name": "unknown",
            "is_required": false,
            "is_known": false
        }
    }
```

**Comment by t-bast** [comment]
This is a known issue and will be fixed in the next release (fixed here: https://github.com/ACINQ/eclair/pull/1253).
The spec explicitly disallowed `var_onion_optin` in invoices, which is why we left it out.
There is a pending PR on the spec to add this feature bit which should be merged soon: https://github.com/lightningnetwork/lightning-rfc/pull/719
