### ISSUE TITLE
Biometric authentication bug 

### ISSUE THREAD

**Issue by C0rteze** [ACINQ/phoenix#187]
I found a bug that doesn't let me access my wallet backgrounds.
I changed the biometrics on my cell phone and after that the app shows the following message: "authentication failed". I can't uninstall and reset because I lost the seed.

My cell phone is a Xiaomi Redmi Note 7 with updated software.

It's a serious problem on the wallet, I hope it can also help other people if there is a solution.

**Comment by dpad85** [comment]
Have you enabled the `Prevent background execution` option in Settings > Security?

If yes, the key encrypting you wallet depends on your biometrics. Changing biometrics will invalidate the key, that's why this option is only available if a backup has been made (there's also a warning).

But to be honest I think this option may just be a footgun. I don't think it is very useful and the drawbacks are very punishing but not obvious (even with warnings and safeguards).

**Comment by C0rteze** [comment]
Oh, I activated this option thought it would help protect the private key. Seeing it this way there really aren't many advantages to activating it, I agree with you.

The good thing is that I missed a few sats so, thanks for the help!
