### ISSUE TITLE
auto closing channels and losing all funds after restoring/transfer

### ISSUE THREAD

**Issue by stefanwouldgo** [ACINQ/phoenix#19]
I just wanted to transfer my phoenix wallet to a new phone. I entered the twelve words while having both instances (old and new) open. This lead to my two channels being closed and all my funds not available anymore. I've now waited two hours or so, hoping that it's just waiting for confirmations. Still the same picture ("Payment for closing channel" x2).  Please help me get back my sats!

**Comment by pm47** [comment]
Hi, can you share your channel data (menu > Channels List > Share all channels), e.g. via email to phoenix@acinq.co?

**Comment by stefanwouldgo** [comment]
The channel list is empty now on both phones.

Pierre-Marie Padiou <notifications@github.com> schrieb am Fr., 10. Jan.
2020, 13:22:

**Comment by pm47** [comment]
Ok, then just the nodeid

**Comment by pm47** [comment]
What happened is that the user had two Phoenix up at the same time, which led one of them to believe it lost its data and ask its peer to force close the channel.

Since it's a remote force close, there is no delay and funds can be immediately recovered on-chain with this procedure:

1. Download Electrum
2. Create a new standard wallet
3. Select "I already have a seed"
4. Enter your 12 words, click on Options and check "BIP39 seed"
5. Select "native segwit (p2wpkh)"
6. Wait for the funds to show up

**Comment by stefanwouldgo** [comment]
Thanks for the quick response. I'll try that asap. Why doesn't Phoenix
itself recognize the funds?

Pierre-Marie Padiou <notifications@github.com> schrieb am Fr., 10. Jan.
2020, 14:15:

**Comment by pm47** [comment]
Because Phoenix doesn't manage on-chain funds, it is a pure LN wallet.

What we could do though is have Phoenix at least tell you that there are funds available on the on-chain addresses associated to its seed, even if it can't directly spend them.
