### ISSUE TITLE
Bug: IOS App wont connect when in wifi

### ISSUE THREAD

**Issue by exitfiat** [ACINQ/phoenix#215]
When I am accessing internet via WiFi on my iPhone the Phoenix wallet won't connect to Lightning peer and Electrum server. The internet connection is fine and on my android device the app works fine in the WiFi.
When switching to mobile data and restarting the app everything works fine.
![IMG_20211027_172611](https://user-images.githubusercontent.com/51097237/139097039-98973c18-fbd4-4932-ac5f-f3c7baf64d55.jpg)

**Comment by robbiehanson** [comment]
That sounds like an issue that's outside of our control. It could be that iOS was having some issue with the WiFi, which was preventing every app on your device from accessing the Internet ?

It's also theoretically possible that your Internet Service Provider was actively blocking access to the Phoenix & Electrum server. Although this is much less likely. Notably because you said you didn't have problems with the WiFi connection on your Android device. Unless, of course, your Android device had TOR enabled, or a VPN.

While we can't fix a WiFi issue, we do realize that the iOS version is currently lacking TOR support. And we're hoping to fix that soon.
