### ISSUE TITLE
Obtainium, installing Phoenix from Github

### ISSUE THREAD

**Issue by anton-isidore** [ACINQ/phoenix#378]
Hi, I am using [Obtainium](https://github.com/ImranR98/Obtainium) to download updates directly from source.

However, on Google Play you have version `1.4.27`, but here on GitHub there is "android-legacy" `1.4.26`.

Why the 1.4.27 is not here at releases as well, why only something called legacy is present? Why is it called legacy? Will this channel (GitHub releases) be supported in the future as well?

Thanks.

**Comment by dpad85** [comment]
Hi, sorry that's an oversight. The tag was already here but I did not publish the release page for version 1.4.27.

> why only something called legacy is present? Why is it called legacy?

The android app is currently called legacy, because it's based on an older version of our lightning engine. It is in the process of being replaced by a [new version](https://acinq.co/blog/phoenix-splicing-update).

> Will this channel (GitHub releases) be supported in the future as well?

Yes, we don't plan to remove the manual apk download. We would also like to support all kind of alternatives to Google Play, but we need time to investigate and do it properly.

**Comment by anton-isidore** [comment]
Great thanks for clarifying!
