### ISSUE TITLE
Camera stays active

### ISSUE THREAD

**Issue by myxmaster** [ACINQ/phoenix#442]
When you click 'Send', the scanner opens and Android status bar indicates camera usage. When you cancel the scanner or go back, Android camera usage indicator stays.

Phoenix Android 2.0.10
Phone: Samsung Galaxy S20+

**Comment by dpad85** [comment]
It looks like this issue is specific to Samsung, I'll investigate.

**Comment by kotasjan** [comment]
@myxmaster is right. I also noticed this bug on my Google Pixel 7 a few days ago. It is IMHO issue of all Android phones. You just don't see it on devices with Android 11 and lower because this new privacy feature was introduced with Android 12. More info about it [here](https://source.android.com/docs/core/permissions/privacy-indicators).

I looked at the code briefly and I will create a pull request. Unfortunately, I didn't manage to build the app and test it because the setup with all the legacy dependencies is quite complex, and I am still running into some issues with Maven. 🥲

Here is the video showing the bug:

https://github.com/ACINQ/phoenix/assets/17073543/4c004bd8-e1da-4b5a-b42e-bf3ea9ebf474

P.S. The hat is there because I didn't have a tool to blur my transactions properly. 😄
