### ISSUE TITLE
I think users should confirm that copied the mnemonic by inserting it on app

### ISSUE THREAD

**Issue by bitcoinuser** [ACINQ/phoenix#49]
I think users should confirm that copied the mnemonic by inserting it on app. Maybe when installing could have the option to skip the backup. But if the user skip it, will always show on main window a message of how important is the backup to not lose bitcoins.

So the phrase: Thanks for using Phoenix. Have you made a backup of your wallet?

could be changed to something like this:

Hi, it's very important to backup your wallet so you don't risk losing your bitcoins.

Like proposed here: https://github.com/ACINQ/phoenix/pull/39/files

**Comment by dpad85** [comment]
The first time User Experience should be welcoming, that's why we did not want to print a scary warning. 

Also, forcing the user to confirm his mnemonic does not work well, people usually find a way around it (like a screenshot) and that can be dangerous.

I think a good middle ground could be to regularly show a notification reminding the user that backups are very important. First version of the app had that, but the notification could not be dismissed so it was quite annoying.
