### ISSUE TITLE
Be able to change app language on Phoenix settings

### ISSUE THREAD

**Issue by bitcoinuser** [ACINQ/phoenix#57]
Be able to change app language on Phoenix settings.

**Comment by dpad85** [comment]
FYI in Android, localization is system wide - and it's not only the strings, but also the dates, number formatting, etc... Apps are supposed to follow the system. It's possible to force an app to use a different locale than the system, but it's not standard and there's some work required.

It's not a priority for us, but a PR would be welcome!

**Comment by robbiehanson** [comment]
Note that in iOS 15, you can now configure language preferences on a per-app basis. This is built into the OS, and not something that needs to be implemented within the app.

<img height="450" src="https://user-images.githubusercontent.com/304604/149005231-622e81a2-fb24-4ebc-9fe4-194f7b2e17b5.PNG">

**Comment by thomak-dev** [comment]
Since Android 13 you can change language on a per app basis: https://support.google.com/android/answer/12395118?hl=en

However, Phoenix doesn't show up in the list.

I would like to change the language in Phoenix to something different than the default system language. I don't care if it's set via the Android settings or in-app.

**Comment by dpad85** [comment]
Thanks for reminding me, the per-app feature is now supported on Android 33. This will be available next release.
