### ISSUE TITLE
Set testnet fee rate to Phoenix testnet wallet

### ISSUE THREAD

**Issue by 4rkad** [ACINQ/phoenix#571]
Currently the miner fees in testnet are higher than in mainnet. Phoenix testnet has always had mainnet values ​​as a reference to establish fees. But right now it makes testing with Phoenix wallet testnet difficult for educational purposes. Could fees be adjusted for testnet? Or even be able to use the wallet with testnet4?

**Comment by dpad85** [comment]
We do plan to use testnet4. We are waiting for https://github.com/bitcoin/bitcoin/pull/29775 to be merged and the update formalised, then we'll switch.

**Comment by dpad85** [comment]
Regarding the feerate, it's been fixed with commit 081e5898. You can download the APK here:
https://acinq.co/pub/phoenix/phoenix-testnet-latest.apk

@robbiehanson The iOS app will keep using the mainnet feerate in some places (cf [MempoolRecommendedResponse](https://github.com/ACINQ/phoenix/blob/081e58985d8e084bbaae094bc0f831b520c691d0/phoenix-ios/phoenix-ios/mempool/MempoolRecommendedResponse.swift#L47)) so let's keep this issue open as a reminder for now, until the iOS app has also been updated.

**Comment by 4rkad** [comment]
Thank u. The new apk works well in testnet3
