### ISSUE TITLE
Unable to scan lightning: URI with Lightning Address

### ISSUE THREAD

**Issue by Liongrass** [ACINQ/phoenix#616]
Hi!

I'm unable to scan a `lightning:` URI QR code with Phoenix wallet (iOS) when the URI points to a Lightning Address.

It works as expected when the `lightning:` URI QR code links to a Bolt11 or LNURL.

Example 1) `lightning:leo@bitcoin.org.hk`
![image](https://github.com/user-attachments/assets/5d2b7467-cab0-4874-8a29-6e7c822999b4)
Error: This appears to be a website (not a lightning invoice)

Example 2) `lightning:leo@send.laisee.org`
![image](https://github.com/user-attachments/assets/dfd2eb8f-cd0f-4aa2-ad38-c4dd18112d93)
Error: This does not appear to be a Lightning invoice

Example 3) `lightning:LNURL1DP68GURN8GHJ7UM9DEJZUMRPD9EK2EFWDAEXWTMVDE6HYMRS9A49QE2SGV6QHV9RY5`
![image](https://github.com/user-attachments/assets/c7066457-48b4-49ef-b90f-9ea48872b7dc)
Success!

**Comment by Liongrass** [comment]
Phoenix iOS Version `2.3.2`

**Comment by pavlenex** [comment]
I second this, we had a LN address QR codes durinng a conference event with over 3000 transactions, Phoenix wallet was one of the few from which people couldn't tip to LN address printed qr. Would be good to get this fixed.

**Comment by dpad85** [comment]
These two URIs are rejected because they mix a `lightning:` prefix with a LNURL-based address. This seems the correct behaviour to me, the expected format is `<username>@<domainname>`. The whole point of human-readable addresses is to make them not technical, short and memorable, so having a URI scheme prefix there does not make sense. Besides, using the `lightning` scheme is not recommended (see [LUD17](https://github.com/lnurl/luds/blob/luds/17.md)).

> I second this, we had a LN address QR codes durinng a conference event with over 3000 transactions, Phoenix wallet was one of the few from which people couldn't tip to LN address printed qr. Would be good to get this fixed.

This could be an unrelated issue, could you share the address that was used?

**Comment by Liongrass** [comment]
The reason why we prefer to prefix `lightning:` to Lightning addresses is that otherwise, when people scan a Lightning address with their phone's integrated camera, they get directed to their email client.

Using the `lightning:` prefix allows the QR code to be scanned with the integrated camera app, they get redirected to their Lightning wallet _and_ they get a visual confirmation of who they are sending money to.

**Comment by dpad85** [comment]
> The reason why we prefer to prefix `lightning:` to Lightning addresses is that otherwise, when people scan a Lightning address with their phone's integrated camera, they get directed to their email client.

That's a good point, I see why the prefix would help. Will fix, thanks for reporting the issue.

Note that you may want to use the `lnurlp:` prefix instead, since the `lightning:` prefix could open a Lightning application that does not handle LNURL payments and would thus reject the address. It's an issue on iOS where the user cannot choose which app opens for a given prefix, so he would be stuck and unable to pay this address.

**Comment by dpad85** [comment]
@TheBlueMatt I understand your point, standardisation matters but try making this otherwise valid point more respectfully.

**Comment by TheBlueMatt** [comment]
Apologies if that came off as disrespectful, I don't believe my comment included any directed insults, and certainly wasn't intended to. Some colorful language aside, I'm actually not sure what in that comment was disrespectful.
