### ISSUE TITLE
Payment fee was below the minimum required by trampoline node - Error

### ISSUE THREAD

**Issue by Q8w3rgxr** [ACINQ/phoenix#77]
All of a sudden my phoenix wallet started to throw this error with every payment. Is there a hidden way to adjust the fees? Right now i dont care if the trampoline node (probably ACINQ) is charging higher fees as long as the payments are possible. Any suggestions? 

<img width="382" alt="Screenshot 2020-06-09 at 10 35 59" src="https://user-images.githubusercontent.com/16136112/84126188-e0d4f080-aa3d-11ea-8921-2d2a87b0494d.png">

**Comment by t-bast** [comment]
Can you copy-paste the `payment_hash` into this issue so that we check our logs?
I suspect that we simply can't forward the payment to the destination because we can't find a route (maybe the channel is unavailable or balance is empty). Unfortunately at the moment, if we can't find a route, we will tell phoenix we want higher fees (because that may allow us to find a different route). We need to do a bit of work to clean up these failing scenario to show the right error to the end user, and I think what you would see once we've finished that clean up is a `route not found` error (but to be confirmed once we have your `payment_hash`).

**Comment by Q8w3rgxr** [comment]
I see, but actually i'm trying to pay my own node which also is connected to ACINQ, so it should only be one hop right? 

Here is the hash: 
a75b4f4dd329fc9d0f37eb99c8c366d0b4a5a62cc78db4cfcd23ba6cab0a706c

Out of interest, how do you find the route with the hash? Is there some sort of explorer?

**Comment by t-bast** [comment]
> Out of interest, how do you find the route with the hash? Is there some sort of explorer or just by looking at your own logs?

We just look at our logs to figure out why the payment wasn't relayed.

> i'm trying to pay my own node which also is connected to ACINQ

We just checked your channels with Acinq, there isn't enough liquidity left for your payment.
Almost all the balance of these channels are on your side, so Acinq can't forward the requested amount. We'll be working on providing better end-user errors in the coming weeks.

**Comment by Q8w3rgxr** [comment]
Rebalanced my channels, now its working. More specified Errors would be great but so far its already a fantastic wallet! Thanks for your help and keep up the good work!
