### ISSUE TITLE
Suggestion: Declareted Fees for OnChain Withdraw

### ISSUE THREAD

**Issue by nicolasssmaia** [ACINQ/phoenix#96]
I am trying Phoenix Wallet, had some coins into it, but today i want to see more about the possibility of take my coins back to my Wallet, doing an on chain transaction.

But i've withdrawed a micro value, like, 200 sat, and don't have any kind of advertise saying how much i should pay in transaction fees, if it will happens or if it's possible wait for a 200 satoshi withdraw onchain.

I suggest a possibility to make an on chain transaction choosing fees, or at least it shows me how much i will pay, or recommends a minnimum value.

:)))

**Comment by pm47** [comment]
Closing your channels, a.k.a. _mutual close_, involves a fee negotiation with your counterparty (our node). Even if you could choose your desired fee setting, it wouldn't be the final one since both sides have to agree on one fee. The good news is that the fee is then shared among both parties, meaning that you typically pay half. FYI our node currently targets 144 blocks for the closing tx.

Another way of controlling the exact fee would be to do a _swap out_ instead of a mutual close. But in that scenario you are paying the full fee amount, so for if you target a particular feerate it may end up more expensive that a regular close.

Hope that helps.
